# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GMUPreload' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GMUPreload

pod 'MJRefresh'
pod 'MJExtension'
pod 'Masonry'
pod 'ReactiveObjC'
  target 'GMUPreloadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GMUPreloadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
